---
- hosts: web
  become: yes
  tasks:

    - name: update
      apt: update_cache=yes

    - name: install apache2
      apt: name=apache2 state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present

    - name: enabled mpm_event
      apache2_module: name=mpm_event state=present

      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarte

    - name: Starting Apache Server
      service:
        name=httpd
        state=stop
      become: true
      become_user: root