---
- hosts: web
  gather_facts: true
  become: true
  tasks:
    - name: "1. Uninstall HTTPD/Apache"
      tags: uninstall_apache
      apt:
        name: httpd
        autoremove: yes
        state: absent