---
- hosts: all
  tasks:
    - name: Get service facts
      setup:
        filter: 'ansible_os_family'
    - name: Print all available facts
      debug:
        var: ansible_facts
    - name: Print all available facts
      debug:
        var: ansible_facts.hostname

 #   - name: Populate service facts
 #     ansible.builtin.service_facts:

    - name: Print all available services
      debug:
        var: ansible_facts.services
#установленные пакеты. Используем package_facts
    - name: Gather the package facts
      package_facts:
        manager: auto
    - name: Print all available packages
      debug:
        var: ansible_facts.packages